version: '3'
services:
  mongo:
    image: mongo:4.0
    volumes:
      - ./mongo/init/:/docker-entrypoint-initdb.d/
      - ./mongo/db/:/data/db/
    restart: always
  brand-report-backend:
    build: ./backend/
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./backend/logs:/var/lib/message/brand-report-backend
    depends_on:
      - mongo